Longest chain zadatak
petrovicdarko1234/zadaci pull request #28
Opened 2023-08-26 10:15 UTC by petrovicdarko1234

https://leetcode.com/problems/maximum-length-of-pair-chain/description/

za logiku neki pola sat,a za jebeno sortiranje po drugi element izgubi 2 sata i na kraj ga ne moga uradim.PLS HELP

2023-08-26 11:39 UTC, sloba-byte requested changes

2023-08-26 11:39 UTC, sloba-byte commented on problems/36.Maximum Length of Pair Chain.gs
> +   for (let j = 1; j < matrix.length; j++) {
let j = i + 1

2023-08-26 12:56 UTC, petrovicdarko1234 commented on problems/36.Maximum Length of Pair Chain.gs
> +   for (let j = 1; j < matrix.length; j++) {
RIP 2 sata zivota  

100%memory 60+ % speed ez

2023-08-27 15:54 UTC, sloba-byte approved these changes
gj

2023-08-29 13:14 UTC, merged